name: covert_connect
description: "Covert connect."
publish_to: 'none'

version: 0.1.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  rust_lib_covert_connect:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  window_manager: 0.5.1
  tray_manager: 0.5.2  
  flutter_launcher_icons: 0.14.4
  bitsdojo_window: 0.1.6
  flutter_acrylic: 1.1.4
  google_fonts: ^7.0.0
  shared_preferences: ^2.5.4
  get_it: ^9.2.0
  freezed_annotation: ^3.1.0
  animated_toggle_switch: ^0.8.7
  fl_chart: ^1.0.0
  collection: ^1.19.1
  toastification: ^3.0.3
  iconsax_flutter: ^1.0.1
  flutter_switch: ^0.3.2
  vector_math: ^2.2.0
  shimmer: 3.0.0
  punycoder: 0.2.2
  ntp: 2.0.0
  package_info_plus: 9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

  freezed: 3.2.0
  build_runner: 2.6.0

flutter:
  assets:
    - assets/icons/
    - assets/images/

# check after run, uses bad resize algorithm (at least for android and windows)
# dart run flutter_launcher_icons
# png to ico https://convertico.com/
flutter_launcher_icons:
  image_path: "assets/images/app-icon.png"
  android: true 
  ios: true
  adaptive_icon_background: "#a0a0a0"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  adaptive_icon_monochrome: "assets/images/app-icon.png"
  image_path_ios_dark_transparent: "assets/images/app-icon-dark.png"
  image_path_ios_tinted_grayscale: "assets/images/app-icon.png"
  remove_alpha_ios: true
  background_color_ios: "#a0a0a0"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true