name: "publish ui"

on:
  workflow_dispatch:
  push:
    branches:
      - app-release

jobs:
  publish-flutter:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: flutter/covert_connect_ui

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        id: version
        with:
          file-path: flutter/covert_connect_ui/pubspec.yaml

      - run: flutter pub get

      - name: Windows build
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release

      - name: Archive Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: ../../../../../../../cc-app-windows-${{ steps.version.outputs.version-number }}.zip
          directory: flutter/covert_connect_ui/build/windows/x64/runner/Release
          exclusions: "*.exp *.lib *.pdb"

      - name: Linux build
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libayatana-appindicator3-dev
          flutter build linux --release

      - name: Archive Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: ../../../../../../../cc-app-linux-${{ steps.version.outputs.version-number }}.zip
          directory: flutter/covert_connect_ui/build/linux/x64/release/bundle

      - name: Macos build
        if: matrix.os == 'macos-latest'
        run: flutter build macos --release

      - name: Archive macOS Artifact
        if: matrix.os == 'macos-latest'
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: ../../../../../../../cc-app-macos-${{ steps.version.outputs.version-number }}.zip
          directory: flutter/covert_connect_ui/build/macos/Build/Products/Release/
          path: ./covert_connect.app

      - name: Add to release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: App release ${{ steps.version.outputs.version-number }}
          files: "*.zip"

